version: '3'

services:
  postgres:
    container_name: lab-05-postgres
    image: bitnami/postgresql:16
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=barber_db
    ports:
      - '5432:5432'
